version: '3.7'

services:
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/post_platform
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=Django
      - POSTGRES_PASSWORD=DjangoPassword123
      - POSTGRES_DB=postgresDB

volumes:
  postgres_data: