FROM python:3.8.3-slim-buster

WORKDIR /usr/src/post_platform

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN pip install --upgrade pip
COPY ./requirements.txt /usr/src/requirements.txt
RUN pip install -r /usr/src/requirements.txt

EXPOSE 8000

COPY . /usr/src/post_platform
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]